# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      nuget-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "Dependencies :arrow_up:"

  - package-ecosystem: "github-actions"
    # For GitHub Actions, you do not need to set the directory to
    # /.github/workflows. Configuring the key to / automatically instructs
    # Dependabot to search the /.github/workflows directory, as well as the
    # action.yml / action.yaml file from the root directory.
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions-dependencies:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "Dependencies :arrow_up:"
