# https://github.com/actions/labeler
":construction_worker: CICD":
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/*
      - .github/labeler.yml

"Documentation :memo:":
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'

"Tests :test_tube:":
  - changed-files:
    - any-glob-to-any-file:
      - tests/**/*
